# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
<% adaptor = ENV['HEROKU_DEPLOYMENT'].nil? ? 'sqlite3' : 'pg' %>

common: &common
  adapter: <%= adaptor %>
  pool: 5
  timeout: 5000


development:
  <<: *common
  database: db/development.sqlite3

test:
  <<: *common
  database: db/test.sqlite3

production:
  <<: *common
  database: db/production.sqlite3
  
